# Generated by Django 4.2.4 on 2023-08-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='name')),
                ('author_surname', models.CharField(max_length=50, verbose_name='surname')),
                ('author_slug', models.SlugField(blank=True, unique=True, verbose_name='author_slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birthdate')),
                ('died_date', models.DateField(blank=True, null=True, verbose_name='died_date')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
    ]
