# Generated by Django 4.2.4 on 2023-08-11 06:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.UUIDField(db_index=True, default=uuid.UUID('03e379ac-68c3-4eb2-bd65-9772d29ebcf9'), primary_key=True, serialize=False, unique=True, verbose_name='book id')),
                ('language', models.CharField(max_length=50, verbose_name='language')),
                ('book_title', models.CharField(max_length=50, verbose_name='book title')),
                ('summary', models.TextField(blank=True, help_text='Summary about the book', max_length=500, null=True, verbose_name='summary')),
                ('book_pages', models.PositiveIntegerField(default=0)),
                ('book_slug', models.SlugField(blank=True, unique=True, verbose_name='book slug')),
                ('in_stock', models.BooleanField(default=False, verbose_name='in_stock')),
                ('available_copies', models.IntegerField(default=0, verbose_name='available_copies')),
                ('book_author', models.ManyToManyField(related_name='bookauthor', to='author.author')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
