# Generated by Django 4.2.4 on 2023-08-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(blank=True, db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='book id'),
        ),
    ]
